/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          50:  '#eef6f1',
          100: '#d4eadd',
          200: '#a8d4bb',
          300: '#6db591',
          400: '#3d9166',
          500: '#1a5c3a',
          600: '#1a5c3a',
          700: '#154d30',
          800: '#0f3d25',
          900: '#0a2d1b',
        },
        earth: {
          50:  '#eef6f1',
          100: '#d4eadd',
          200: '#a8d4bb',
          300: '#6db591',
          400: '#3d9166',
          500: '#1a5c3a',
          600: '#1a5c3a',
          700: '#154d30',
          800: '#0f3d25',
          900: '#0a2d1b',
        },
      },
      fontFamily: {
        display: ['"Playfair Display"', 'Georgia', 'serif'],
        body:    ['"DM Sans"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      animation: {
        'fade-in':      'fadeIn 0.5s ease-out',
        'slide-up':     'slideUp 0.4s ease-out',
        'slide-in':     'slideIn 0.3s ease-out',
        'float-a':      'floatA 3.8s ease-in-out infinite',
        'float-b':      'floatB 4.2s ease-in-out infinite',
        'float-c':      'floatC 3.5s ease-in-out infinite',
        'float-d':      'floatD 4.5s ease-in-out infinite',
        'float-center': 'floatCenter 4s ease-in-out infinite',
      },
      keyframes: {
        fadeIn:      { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        slideUp:     { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        slideIn:     { '0%': { opacity: '0', transform: 'translateX(-10px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        floatA:      { '0%, 100%': { transform: 'translateY(0px)' },               '50%': { transform: 'translateY(-7px)' } },
        floatB:      { '0%, 100%': { transform: 'translateY(-4px)' },              '50%': { transform: 'translateY(5px)' } },
        floatC:      { '0%, 100%': { transform: 'translateY(0px)' },               '50%': { transform: 'translateY(-6px)' } },
        floatD:      { '0%, 100%': { transform: 'translateY(-3px)' },              '50%': { transform: 'translateY(6px)' } },
        floatCenter: { '0%, 100%': { transform: 'translate(-50%, -50%) translateY(0px)' }, '50%': { transform: 'translate(-50%, -50%) translateY(-10px)' } },
      },
    },
  },
  plugins: [],
};